### ISSUE TITLE
Dense Redstone Ore dropping untextured redstones

### ISSUE THREAD

**Issue by SwiftingDuster** [YOYOK9/BusinessElite-Plus#10]
As the title says, mining dense redstone ore drops redstone but it's untextured (Default Purple/Black cube). However it gives you redstone when you pick it up and the texture is still intact even if you drop it again.

**Comment by YOYOK9** [comment]
I am aware of this issue, there is an npc at spawn that can trade the redstone. Or if u put it into a crafting table you can convert it to normal redstone

**Comment by SwiftingDuster** [comment]
The problem is that the item spawned in the world when you break the dense ore is untextured, however it correctly gives redstone when you pick it up.
