### ISSUE TITLE
[Official] Direwolves spawning in houses/lit areas

### ISSUE THREAD

**Issue by CaptainLucster** [YOYOK9/BusinessElite-Plus#12]
In the plains biome dire wolves (hostile enemies) spawn in lit areas at night.

**Comment by YOYOK9** [comment]
Dire wolves are considered passive. But just dont like people. Their spawn rate is correct i believe

**Comment by YOYOK9** [comment]
Supposed to be this way.

**Comment by CaptainLucster** [comment]
Wait the are sopposed to spawn IN tour house?!

**Comment by YOYOK9** [comment]
See you didn't strait that....

**Comment by CaptainLucster** [comment]
Thats what i ment by lit area

**Comment by YOYOK9** [comment]
Say that next time

**Comment by YOYOK9** [comment]
Possibly fixed. Lowered spawn biomes and amount spawned.
