### ISSUE TITLE
Applied energistics 2 broken

### ISSUE THREAD

**Issue by CaptainLucster** [YOYOK9/BusinessElite-Plus#15]
#### Issue Description:

The Inscriber and silicon recipes don't work.

#### What Happens:

-> When you put a pattern in the inscriber it spits it back out.
-> When you try to put certus quartz dust in a furnace (even though there is a recipe for it in jei) nothing happens. refined storage also has a silicon recipe that is much cheaper so I recommend making that the only one if that maxes the fix easier.

#### What you Expected to happen:

1. The inscriber to work and inscribe stuff
2.the certus dust to turn into silicon

#### Steps to Reproduce:

Try using the inscriber.
Try making silicon with certus dust.

#### Does it happen on the Server:

yes

#### Pack/Mods Versions:

Applied energistics 2

#### Your most recent log file where the issue was present: 

lul wut does this be?

[Pastebin/Gist/Pictures LINK here]

**Comment by YOYOK9** [comment]
this report makes absolutely no sense reading it... Need more info on what all is going on.... and what version of the pack your on

**Comment by YOYOK9** [comment]
made Ae2 silicon by crushing sand in a mekanism crusher
