### ISSUE TITLE
Died and lost everything

### ISSUE THREAD

**Issue by JJVG2001** [YOYOK9/BusinessElite-Plus#17]
#### Issue Description:
Right clicked the grave with the key and only dropped one feather, also two graves were created where I died instead of one, and both dropped a feather.

#### What Happens:
When you right click the grave with the key it is supposed to give you the items you had when you died.

#### What you Expected to happen:

1.I would get my items
2.That the items would atleast be dropped and I could get them back
3.
...
#### Steps to Reproduce:
I tried to jump into a hole and missed because my boots were out of energy and the fall damage was applied. Then I opened both graves with the keys I had in my inventory

#### Does it happen on the Server:

yes

#### Your most recent log file where the issue was present: 

[Pastebin/Gist/Pictures LINK here]

**Comment by YOYOK9** [comment]
This should be fixed in the newest version of the pack. can u give me a list of all that was lost?

**Comment by YOYOK9** [comment]
Fixed
