### ISSUE TITLE
Bronze Helmet

### ISSUE THREAD

**Issue by Hunter13004** [YOYOK9/BusinessElite-Plus#19]
#### Issue Description:
gives you an orange nose for some reason

#### What Happens:
when you wear a bronze helmet an orange 2x1 pixel thing appears on your face

#### What you Expected to happen:
1. a full rectangle coming down from the helmet
2. nothing there at all
#### Steps to Reproduce:
1. put on a bronze helmet
2. look at yourself or have someone look at you

#### Does it happen on the Server:
yes

#### Pack/Mods Versions: Ex(V1.5.3)
(DO NOT LEAVE BLANK) 
1.9.2

#### Your most recent log file where the issue was present:  ex(log folder or crash reports)
(do not leave blank)
(not necessary its a graphical glitch for all)
[Pastebin/Gist/Pictures LINK here]
![unknown](https://user-images.githubusercontent.com/34967791/34456773-bd3c139a-ed6d-11e7-9961-eeb76d89a0f4.png)

**Comment by YOYOK9** [comment]
Need the mod it is from.
