### ISSUE TITLE
Disappearing Items

### ISSUE THREAD

**Issue by CaptainLucster** [YOYOK9/BusinessElite-Plus#21]
#### Issue Description:

Items.... well..... as you guessed...... disappear

#### What Happens:

Items disappear

#### What you Expected to happen:

Items to not disappear

#### Steps to Reproduce:

hit put items in inventory crafting grid and close and have many of the same item with hand filler and place some

#### Does it happen on the Server:

yes

#### Pack/Mods Versions: Ex(V1.5.3)

1.9.2 server
no clue what mod(s)

**Comment by YOYOK9** [comment]
Mod is inventory tweaks. And mossibly mouse tweaks. Will look into it. 

When you say "hit put items" is this a keyboard button or a gui button in game?

**Comment by CaptainLucster** [comment]
The hit is a typo i meant pit items in your crafting grid
