### ISSUE TITLE
Glitch involving EnderIO dark steel shield and claims

### ISSUE THREAD

**Issue by Nim10** [YOYOK9/BusinessElite-Plus#26]
#### Issue Description:
In yoyok9's claim X=-1611, Z=484, Y=13, I can't use my Dark Shield (Ender IO) in my offhand to shield myself.

#### What Happens:
Shield shows as shielding me for a brief moment, then stops shielding.

I get the message in Minecraft chat: you can't use the item enderio:item_dark_steel_shield in this claim. If I am holding something in my main hand and left click (to shield), I receive this additional message: you don't have yoyok9's permission to interact with the item (for example:) tconstruct:pickaxe.

#### What you Expected to happen:
Shield to shield me

#### Steps to Reproduce in detail:
1. Go to yoyok9's claim; coordinates x=-1611, z=484, y=13
2. place dark steel shield in offhand
3. attempt to shield self (with left click)

#### Does it happen on the Server:
Yes

#### Pack Versions: Ex(V1.5.3)
V0.2.4.1

#### Mods Effected: Ex(ex Nihilo, AE2) 
EnderIO; claims

#### Your most recent log file where the issue was present:  ex(log folder or crash reports)
(do not leave blank. If you dont know ask for help)

https://gist.github.com/Nim10/565c58f80eeb7bddedb80d59da02779b

**Comment by YOYOK9** [comment]
Can I have a screen shot of the issue? Log has no mention of chat.

**Comment by YOYOK9** [comment]
Fixed
