### ISSUE TITLE
Will not open mod pack after loading sceen

### ISSUE THREAD

**Issue by Icequeenz** [YOYOK9/BusinessElite-Plus#28]
#### Steps to Reproduce in detail:
1.
2.
3.
...
#### Pack Versions: 1.1.3
(DO NOT LEAVE BLANK) 

#### Mods Effected: Idk
(DO NOT LEAVE BLANK)

#### Your most recent log file where the issue was present or a screenshot of the issue:  ex(log folder or crash reports or screenshot folder)
(do not leave blank. If you dont know ask for help)

[Pastebin/Gist/Pictures LINK here]
[crash-2020-04-05_10.38.55-client.txt](https://github.com/YOYOK9/BusinessElite-Plus/files/4434461/crash-2020-04-05_10.38.55-client.txt)

**Comment by YOYOK9** [comment]
Ran out of memory, increase the amount allocated to the pack. If on twitch launcher: https://github.com/YOYOK9/BusinessElite-Plus/wiki/Allocating-Memory
