### ISSUE TITLE
When Players travel to a different dimension (nether, end) they are stuck there[Bug]

### ISSUE THREAD

**Issue by stormtrooperxl** [YOYOK9/BusinessElite-Plus#32]
#### What Happens:
none of the teleport commands (/spawn, /home) work, portals do not work

#### Steps to Reproduce in detail:
1.
2.
3.
...
#### Does it happen on the Server: (yes or no)
[ ] Yes

[ ] No

#### Pack Versions: Ex(V165.1.0.1)
(DO NOT LEAVE BLANK) 

#### Mods Effected: Ex: (Quark, AE2, ect) 
(DO NOT LEAVE BLANK)

#### Your most recent log file where the issue was present or a screenshot of the issue:  ex: (log folder or crash reports or screenshot folder)
(do not leave blank. If you dont know ask for help in our discord)

[Pastebin/Gist/Pictures LINK here]

**Comment by YOYOK9** [comment]
"Elrol_Arrowsend — Thursday 18th at 7:49 PM
It was an issue i was seeing on my end where it would put the player in a state of forever loading. However i was told that others hadnt had the issue. So i will add it as a toggle in the next update"

**Comment by YOYOK9** [comment]
Temp fix: Added portal to spawn in the end, the nether will need to be done the old fashion way (vanilla)

**Comment by YOYOK9** [comment]
Newest update of server utiles fixed the servers issue, Client will come eventually

**Comment by YOYOK9** [comment]
Fixed on both sides
