### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DeadBringerX** [YOYOK9/BusinessElite-Plus#33]
#### Issue Description:
Ore Dictionary Fix

#### What Happens:
Ores Turn into Pedestal version of dust that isn't compatible with Mekanism, 
#### What you Expected to happen:
Ore Dict compatible so it smelts and turn into either Mek or thermal version of Ingot
#### Steps to Reproduce in detail:
1. Ore in enrichment or any grinder
2. Look in the damn chest and be calm
3. Look at the factory not working then Panic
4. Make a bug report to Yoyo then wait
...
#### Does it happen on the Server: (yes or no)
[ ] Yes <- This

[ ] No

#### Pack Versions: Ex(V165.1.0.1)
(DO NOT LEAVE BLANK) 
165.1.7 <- thats what yoyo said he thought
#### Mods Effected: Ex: (Quark, AE2, ect) 
(DO NOT LEAVE BLANK)
Pedestal Mod, Mekanism

#### Your most recent log file where the issue was present or a screenshot of the issue:  ex: (log folder or crash reports or screenshot folder)
(do not leave blank. If you dont know ask for help in our discord)

[Pastebin/Gist/Pictures LINK here]

**Comment by YOYOK9** [comment]
Fixed in next update
