### ISSUE TITLE
Nether resets and removes placed blocks[Bug]

### ISSUE THREAD

**Issue by Urbanautters** [YOYOK9/BusinessElite-Plus#35]
Please Name your issue above ^^^^^^: [bug] NAME OF ISSUE
#### Issue Description:
I had placed a tier 2 enviromental tech miner in the nether, but I forgot a few blocks. I went back to grab them and as soon as I returned, less than 30 seconds later the miner was gone. I've tested several times and the blocks I place don't always disappear on the first re-entry, but might after a time or two.

#### What Happens:
Blocks disappear

#### What you Expected to happen:
Blocks to stay there..

#### Steps to Reproduce in detail:
1.
2.
3.
...
#### Does it happen in Single Player: (yes or no)
[ ] Yes

[ ] No

#### Does it happen on the Server: (yes or no)
[ X ] Yes

[ ] No

#### Pack Versions: Ex(V165.1.0.1)
165.1.9

#### Mods Effected: Ex: (Quark, AE2, ect) 
Vanilla, Enviro tech, possibly others

#### Your most recent log file where the issue was present or a screenshot of the issue:  ex: (log folder or crash reports or screenshot folder)

https://gist.github.com/Urbanautters/ddbdb8b3c30003c36a985b3631ead2e2

**Comment by Urbanautters** [comment]
yoyo and I possibly found out it was a world bug around my portal.. theoretically fixed by just going a ways away.

**Comment by YOYOK9** [comment]
Fixed in newest update
