### ISSUE TITLE
[REQ] Ankh Timer

### ISSUE THREAD

**Issue by Hilers** [YOYOK9/BusinessElite-Plus#38]
**Mod request**
Is there a mod you feel would be a good addition to the pack? Tell us what it is and why you feel it would be a good addition.

Mod: Corail Tombstone (Already there)
Reason: Is it possible to lower the timer from 2.5 hours to less time, around 5 minutes?

###Note: BE+ is a Tech based modpack, meaning we do not have Magic based mods. Tech Only

**Comment by YOYOK9** [comment]
Timer for what?

**Comment by Hilers** [comment]
whenever the ankh from corail tombstones is used, it has a 3hr cooldown, I was wondering if that time could be lowered

**Comment by YOYOK9** [comment]
We will not be lowering the timer, lots of other things you can do in the pack while you wait.
