### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Hilers** [YOYOK9/BusinessElite-Plus#39]
Please Name your issue above ^^^^^^: [bug] UI Opening Issue
#### Steps to Reproduce in detail:
1. Trying to open Certain UI
2. 
3. 
...
#### Does it happen in Single Player: (yes or no)
[ ] Yes

[ ] No

#### Does it happen on the Server: (yes or no)
[ x] Yes

[ ] No

#### Pack Versions: Ex(V165.1.0.1)
(DO NOT LEAVE BLANK)  165.1.1.1

#### Mods Effected: Ex: (Quark, AE2, ect) 
(DO NOT LEAVE BLANK) Simple Storage Network, Mekanism, Trash Cans, Etc

#### Your most recent log file where the issue was present or a screenshot of the issue:  ex: (log folder or crash reports or screenshot folder)
(do not leave blank. If you dont know ask for help in our discord)

[Pastebin/Gist/Pictures LINK here]

**Comment by YOYOK9** [comment]
Need pictures, and test on sp.

**Comment by YOYOK9** [comment]
Closing due to lack of info, create a new post if this is still an issue
