### ISSUE TITLE
Shift Clicking fish into soul extractor caused client crash[Bug]

### ISSUE THREAD

**Issue by Urbanautters** [YOYOK9/BusinessElite-Plus#41]
Please Name your issue in the bar above ^^^^^^:EX: [bug] NAME OF ISSUE
#### Issue Description:
I shift clicked raw fish into the soul extractor from Mystical Agriculture and my client crashed

#### What Happens:
The client closes

#### What you Expected to happen:
I expected the item to go into the machine and work properly.

#### Steps to Reproduce in detail:
1.open gui for soul extractor
2.shift click fish (or other items into a mystical agriculture machine as i found out earlier with seeds too)
3.
...
#### Does it happen in Single Player: (yes or no) Please test
[ ] Yes

[X ] No

#### Does it happen on the Server: (yes or no)
[X] Yes

[ ] No

#### Pack Versions: Ex(V165.1.0.1)
(DO NOT LEAVE BLANK) 
1.15.5-2.0.18
#### Mods Effected: Ex: (Quark, AE2, ect) 
(DO NOT LEAVE BLANK)
Mystical Agriculture

#### Your most recent log file where the issue was present or a screenshot of the issue:  ex: (log folder or crash reports or screenshot folder)
(DO NOT LEAVE BLANK. If you dont know ask for help in our discord)

[Pastebin/Gist/Pictures LINK here]

https://pastebin.com/hNeq4XM4

**Comment by YOYOK9** [comment]
Old pack version - no longer supported
