### ISSUE TITLE
Compact Drawer Duplication Bug

### ISSUE THREAD

**Issue by Foogii** [YOYOK9/BusinessElite-Plus#42]
Please Name your issue in the bar above ^^^^^^:EX: [bug] NAME OF ISSUE
#### Issue Description:
Items can be duplicated using compact storage drawers.

#### What Happens:
When placing items into a compact drawer, all numbers will be in sync with one another. You can then input the small material (ex 1 iron bar), and receive an iron block for it.

#### What you Expected to happen:
What should normally happen would be for 9 bars to convert to 1 block of iron, not a 1:1 ratio.

#### Steps to Reproduce in detail:
1. Input condensed material (ex. iron block).
2. If all the numbers match up (ex. 1 block, 1 bar, 1 ingot), input and extra bar.
3. If all numbers are still the same, you may take out an iron block, convert it into 9 bars and put it them back into the drawer. There should then be an extra 9 blocks in the drawer, as if the conversion ratio was 1:1.
...
#### Does it happen in Single Player: (yes or no) Please test
[x ] Yes

[ ] No

#### Does it happen on the Server: (yes or no)
[x ] Yes

[ ] No

#### Pack Versions: Ex(V165.1.0.1)
1.16.5-2.1.14

#### Mods Effected: Ex: (Quark, AE2, ect) 
Storage Drawers

#### Your most recent log file where the issue was present or a screenshot of the issue:  ex: (log folder or crash reports or screenshot folder)
(DO NOT LEAVE BLANK. If you dont know ask for help in our discord)

https://gyazo.com/a6ecf002daf590e1564f3d784342e8ba
^
Gif of the issue.

[Pastebin/Gist/Pictures LINK here]

**Comment by YOYOK9** [comment]
Fixed in latest update
