### ISSUE TITLE
[crash] exit code -1073740940

### ISSUE THREAD

**Issue by Berndarmin** [YOYOK9/BusinessElite-Plus#44]
Please Name your issue in the bar above ^^^^^^:EX: [bug] NAME OF ISSUE
#### What Happens: cr
[latest.log](https://github.com/YOYOK9/BusinessElite-Plus/files/10268979/latest.log)
ash to desk top with in a few sec of loading the world get exit code -1073740940 no other info
got exit code -1 after 3rd try 

#### Steps to Reproduce in detail:
1.
2.
3.
...
#### Does it happen in Single Player: (yes or no) Please test
[ ] Yes

[x] No

#### Does it happen on the Server: (yes or no)
[x] Yes

[ ] No

#### Pack Versions: Ex(V165.1.0.1)
1.19.2-0.0.7
#### Mods Effected: Ex: (Quark, AE2, ect) 
unknowen

#### Your most recent log file where the issue was present or a screenshot of the issue:  ex: (log folder or crash reports or screenshot folder)
(DO NOT LEAVE BLANK. If you dont know ask for help in our discord)

[Pastebin/Gist/Pictures LINK here]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffca967df36, pid=14424, tid=2768
#
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x79df36]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
#

---------------  S U M M A R Y ------------

Command Line: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Dos.name=Windows 10 -Dos.version=10.0 -Xss1M -Djava.library.path=C:\CurseForge\Install\bin\5f1d5304efd8e6213641006ca511e06c9a4d39c3 -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.3.522 -Djava.net.preferIPv6Addresses=system -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,JarJarFileSystems,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,forge-43.2.1.jar,forge-43.2.1 -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar -DlibraryDirectory=C:\CurseForge\Install\libraries --module-path=C:\CurseForge\Install\libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar;C:\CurseForge\Install\libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar;C:\CurseForge\Install\libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar;C:\CurseForge\Install\libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar;C:\CurseForge\Install\libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar;C:\CurseForge\Install\libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar;C:\CurseForge\Install\libraries/org/ow2/asm/asm/9.3/asm-9.3.jar;C:\CurseForge\Install\libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar --add-modules=ALL-MODULE-PATH --add-opens=java.base/java.util.jar=cpw.mods.securejarhandler --add-opens=java.base/java.lang.invoke=cpw.mods.securejarhandler --add-exports=java.base/sun.security.util=cpw.mods.securejarhandler --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming -Xmx10112m -Xms256m -Dminecraft.applet.TargetDirectory=C:\CurseForge\Instances\BE+ 1.19.2 Builder -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -Dlog4j.configurationFile=C:\CurseForge\Install\assets\log_configs\client-1.12.xml cpw.mods.bootstraplauncher.BootstrapLauncher --username berndarmin --version forge-43.2.1 --gameDir C:\CurseForge\Instances\BE+ 1.19.2 Builder --assetsDir C:\CurseForge\Install\assets --assetIndex 1.19 --uuid f2e797d432004b979964ae29e5f0b35e --clientId NTc4ZWU3ZDAtNzE2Mi00MWJmLThmZTItYmMxMzVmNWZlN2Ni --xuid 2533274864796042 --userType msa --versionType release --width 1024 --height 768 --launchTarget forgeclient --fml.forgeVersion 43.2.1 --fml.mcVersion 1.19.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220805.130853

Host: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, 12 cores, 15G,  Windows 10 , 64 bit Build 19041 (10.0.19041.2364)
Time: Tue Dec 20 08:51:29 2022 Eastern Standard Time elapsed time: 375.333482 seconds (0d 0h 6m 15s)

---------------  T H R E A D  ---------------

Current thread (0x000002426e197de0):  VMThread "VM Thread" [stack: 0x0000007fb4400000,0x0000007fb4500000] [id=2768] _threads_hazard_ptr=0x000002430585e770

Stack: [0x0000007fb4400000,0x0000007fb4500000],  sp=0x0000007fb44ff450,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x79df36]
V  [jvm.dll+0x34b349]
V  [jvm.dll+0x34cde8]
V  [jvm.dll+0x34b710]
V  [jvm.dll+0x8387cb]
V  [jvm.dll+0x839504]
V  [jvm.dll+0x839a4c]
V  [jvm.dll+0x839df4]
V  [jvm.dll+0x839ec0]
V  [jvm.dll+0x7e22da]
V  [jvm.dll+0x676065]
C  [ucrtbase.dll+0x21bb2]
C  [KERNEL32.DLL+0x17614]
C  [ntdll.dll+0x526a1]

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0xffffffffffffffff

Register to memory mapping:

RIP=0x00007ffca967df36 jvm.dll
RAX=0x3e0000003d800000 is an unknown value
RBX=0x00000242b6cfef20 is a thread
RCX=0x00000242b6cfef20 is a thread
RDX=0x00000242b6cfef20 is a thread
RSP=0x0000007fb44ff450 points into unknown readable memory: 0x0000000000000000 | 00 00 00 00 00 00 00 00
RBP=0x00000242b6cfef20 is a thread
RSI=0x0 is NULL
RDI=0x0000007fb4dffb00 is pointing into the stack for thread: 0x000002426e284f50
R8 =0x00007ffca98a2578 jvm.dll
R9 =0x00000242b6cfef20 is a thread
R10=0x0 is NULL
R11=0x0000007fb44fec70 points into unknown readable memory: 0x0000f19c66c7c15b | 5b c1 c7 66 9c f1 00 00
R12=0x00007ffca983ea98 jvm.dll
R13=0x0000007fb4dffa78 is pointing into the stack for thread: 0x000002426e284f50
R14=0x0000000000000061 is an unknown value
R15=

**Comment by YOYOK9** [comment]
Please follow the issues outline (correctly), Create a new issues post and try again.
