### ISSUE TITLE
Chester

### ISSUE THREAD

**Issue by CaptainLucster** [YOYOK9/BusinessElite-Plus#6]
Whenever you break a chest that has items in it, there is a chance that one type of item is deleted regardless of how many stacks of said item are in the chest.

**Comment by YOYOK9** [comment]
Probably clear lag. Need a list of items lost

**Comment by CaptainLucster** [comment]
~4 stacks of iron ingots and ~6 stacks of tin ingots

**Comment by YOYOK9** [comment]
added the ingots and a few vanilla ores to the clear whitelist. Hopefully that fixes that issue
